# Configs the mapping of joints with real devices
# Define the different types of interfaces
types: [ gazebo_position]
# prl120_waist: { name: waist, type: ipa_can_open, joints: [waist_joint], state_topic: /waist_controller/state, command_topic: /waist_controller/command_vel}

#bhand_left: { name: left_gripper, type: bhand, joints: ['bh_j12_joint', 'bh_j23_joint', 'bh_j33_joint', 'bh_j32_joint', 'bh_j22_joint', 'bh_j11_joint', 'bh_j13_joint', 'bh_j21_joint'], state_topic: /bhand/state, command_topic: /bhand/command}
#wsg50_right: { name: right_gripper, type: wsg50_gripper, joints: [wsg_50_finger_1_start_joint, wsg_50_finger_2_start_joint], state_topic: /wsg_50/status, command_topic: /wsg_50/command, init_service: /wsg_50/init, recovery_service: /wsg_50/ack}



groups: { 
 arm_j1: { name: arm_j1, type: gazebo_position, joints: [j1], command_topic: /rb1_arm/j1_position_controller/command},
 arm_j2: { name: arm_j2, type: gazebo_position, joints: [j2], command_topic: /rb1_arm/j2_position_controller/command},
 arm_j3: { name: arm_j3, type: gazebo_position, joints: [j3], command_topic: /rb1_arm/j3_position_controller/command},
 arm_j4: { name: arm_j4, type: gazebo_position, joints: [j4], command_topic: /rb1_arm/j4_position_controller/command},
 arm_j5: { name: arm_j5, type: gazebo_position, joints: [j5], command_topic: /rb1_arm/j5_position_controller/command},
 arm_j6: { name: arm_j6, type: gazebo_position, joints: [j6], command_topic: /rb1_arm/j6_position_controller/command},
 arm_j7: { name: arm_j7, type: gazebo_position, joints: [j7], command_topic: /rb1_arm/j7_position_controller/command}
}

# 
#  
